### ISSUE TITLE
有几个缺少模块

### ISSUE THREAD

**Issue by linyanshan0305** [l499477004/JD-scripts#13]
_错误日志_
Cannot find module '/home/runner/scripts/jd_jxstory.js'
Error: Cannot find module '/home/runner/scripts/jd_collectProduceScore.js'
Error: Cannot find module '/home/runner/scripts/jd_split.js'

**Comment by l499477004** [comment]
以上活动已结束，对应的脚本文件已移除。请删除对应的yml文件，或重新fork

**Comment by linyanshan0305** [comment]
好的，谢谢
