### ISSUE TITLE
听说白嫖不够还要再蹭点流量？

### ISSUE THREAD

**Issue by sallyciel** [l499477004/JD-scripts#25]
见过不要脸的，还真没见过这么不要碧莲的，长见识，fork一下可以，搬运可以，开源精神嘛，替换人家互助码也行，但能有点节操申明下那是你自己的吗？最后这赞赏码，呵呵，骚年，知道作者用的啥开源协议不？真替你害臊！

**Comment by l499477004** [comment]
> 见过不要脸的，还真没见过这么不要碧莲的，长见识，fork一下可以，搬运可以，开源精神嘛，替换人家互助码也行，但能有点节操申明下那是你自己的吗？最后这赞赏码，呵呵，骚年，知道作者用的啥开源协议不？真替你害臊！

https://github.com/l499477004/JD-scripts/issues/32#issue-839687129
