### ISSUE TITLE
无语了。

### ISSUE THREAD

**Issue by CarolineNS** [l499477004/JD-scripts#27]
![Screenshot_20210324-193105~2](https://user-images.githubusercontent.com/50624036/112303796-aa6c1780-8cd7-11eb-81b7-235e8e23e411.jpg)

**Comment by l499477004** [comment]
> ![Screenshot_20210324-193105~2](https://user-images.githubusercontent.com/50624036/112303796-aa6c1780-8cd7-11eb-81b7-235e8e23e411.jpg)
> 
> 

https://github.com/l499477004/JD-scripts/issues/32#issue-839687129
