### ISSUE TITLE
？

### ISSUE THREAD

**Issue by eatumom** [l499477004/JD-scripts#30]
？

**Comment by l499477004** [comment]
https://github.com/l499477004/JD-scripts/issues/32#issue-839687129

**Comment by eatumom** [comment]
麻烦删除这条issue吧

**Comment by eatumom** [comment]
> 脸呢
> 脸呢
> 脸呢
> 脸呢

**Comment by eatumom** [comment]
求求你给我删了这个issue吧 球球了球球了
