### ISSUE TITLE
docker 方式一启动出错

### ISSUE THREAD

**Issue by lxmicode** [l499477004/JD-scripts#9]
按照教程docker方式一启动出错，具体信息如下，尝试调整无果，求助。

错误信息
ERROR: yaml.scanner.ScannerError: while scanning a simple key
  in "./docker-compose.yml", line 42, column 9
could not find expected ':'
  in "./docker-compose.yml", line 43, column 9

配置如下
![image](https://user-images.githubusercontent.com/43111963/101576647-4b2e1400-3a14-11eb-909f-da4e17faaba6.png)

**Comment by l499477004** [comment]
> 按照教程docker方式一启动出错，具体信息如下，尝试调整无果，求助。
> 
> 错误信息
> ERROR: yaml.scanner.ScannerError: while scanning a simple key
> in "./docker-compose.yml", line 42, column 9
> could not find expected ':'
> in "./docker-compose.yml", line 43, column 9
> 
> 配置如下
> ![image](https://user-images.githubusercontent.com/43111963/101576647-4b2e1400-3a14-11eb-909f-da4e17faaba6.png)

图片看不了，仔细检查一下你的配置，特别检查定时任务文件名称crontab_list.sh是否与配置文件中名称一致

不建议使用docker部署，docker脚本更新会不及时，建议使用方法四github actions部署

**Comment by lxmicode** [comment]
https://user-images.githubusercontent.com/43111963/101576647-4b2e1400-3a14-11eb-909f-da4e17faaba6.png。 这是图片地址，跟官方配置基本一致

**Comment by lxmicode** [comment]
好的，我试试github actions

**Comment by lxmicode** [comment]
换 github actions 方式
